    ["apollosv8"] = {
        name = "apollosv8", 
        label = "Apollos v8", 
        weight = 500, 
        stackable = false, 
        description = "",
    },
    ["avesvv12"] = {
        name = "avesvv12",
        label = "Avesv V12",
        weight = 500,
        stackable = false,
        description = "",
    },
    ["cummins"] = {
        name = "cummins",
        label = "cummins",
        weight = 500,
        stackable = false,
        description = "",
    },
    ["diablov12"] = {
        name = "diablov12",
        label = "Diablo V12",
        weight = 500,
        stackable = false,
        description = "",
    },
    ["f40v8"] = {
        name = "f40v8",
        label = "F40 V8",
        weight = 500,
        stackable = false,
        description = "",
    },
    ["f50v12"] = {
        name = "f50v12",
        label = "F50 V12",
        weight = 500,
        stackable = false,
        description = "",
    },
    ["ferrarif12"] = {
        name = "ferrarif12",
        label = "Ferrari F12",
        weight = 500,
        stackable = false,
        description = "",
    },
    ["gt3flat6"] = {
        name = "gt3flat6",
        label = "GT3 Flat 6",
        weight = 500,
        stackable = false,
        description = "",
    },
    ["gtaspanov10"] = {
        name = "gtaspanov10",
        label = "Spano V10",
        weight = 500,
        stackable = false,
        description = "",
    },
    ["k20a"] = {
        name = "k20a",
        label = "K20a Type R",
        weight = 500,
        stackable = false,
        description = "",
    },
    ["lambov10"] = {
        name = "lambov10",
        label = "Lambo v10",
        weight = 500,
        stackable = false,
        description = "",
    },
    ["m158huayra"] = {
        name = "m158huayra",
        label = "Huayra",
        weight = 500,
        stackable = false,
        description = "",
    },
    ["m297zonda"] = {
        name = "m297zonda",
        label = "M297 ZONDA",
        weight = 500,
        stackable = false,
        description = "",
    },
    ["mclarenv8"] = {
        name = "mclarenv8",
        label = "Mclaren V8",
        weight = 500,
        stackable = false,
        description = "",
    },
    ["murciev12"] = {
        name = "murciev12",
        label = "Murcie V12",
        weight = 500,
        stackable = false,
        description = "",
    },
    ["musv8"] = {
        name = "musv8",
        label = "Mustang V8",
        weight = 500,
        stackable = false,
        description = "",
    },
    ["perfov10"] = {
        name = "perfov10",
        label = "Perfo V10",
        weight = 500,
        stackable = false,
        description = "",
    },
    ["predatorv8"] = {
        name = "predatorv8",
        label = "Predator v8",
        weight = 500,
        stackable = false,
        description = "",
    },
    ["r35sound"] = {
        name = "r35sound",
        label = "GTR 35",
        weight = 500,
        stackable = false,
        description = "",
    },
    ["r488sound"] = {
        name = "r488sound",
        label = "R488",
        weight = 500,
        stackable = false,
        description = "",
    },
    ["rotary7"] = {
        name = "rotary7",
        label = "Rotary 7",
        weight = 500,
        stackable = false,
        description = "",
    },
    ["sestov10"] = {
        name = "sestov10",
        label = "Sesto V10",
        weight = 500,
        stackable = false,
        description = "",
    },
    ["shonen"] = {
        name = "shonen",
        label = "Shonen Engine",
        weight = 500,
        stackable = false,
        description = "",
    },
    ["supra2jzgtett"] = {
        name = "supra2jzgtett",
        label = "Supra 2JZ GTE Twin Turbo",
        weight = 500,
        stackable = false,
        description = "",
    },
    ["urusv8"] = {
        name = "urusv8",
        label = "Urus V8",
        weight = 500,
        stackable = false,
        description = "",
    },
    ["v8engine"] = {
        name = "v8engine",
        label = "Brabus 850",
        weight = 500,
        stackable = false,
        description = "",
    },
    ["veyronsound"] = {
        name = "veyronsound",
        label = "Veyron",
        weight = 500,
        stackable = false,
        description = "",
    },
    ["viperv10"] = {
        name = "viperv10",
        label = "Viper V10",
        weight = 500,
        stackable = false,
        description = "",
    },
}
